name: Generate a microprint visualizer
description: Creates an html file for visualizing the microprint in detail

runs:
  using: docker
  image: 'Dockerfile'


branding:
  icon: file-text
  color: green 

